project:
  name: robust-skin-lesion-segmentation-isic2018-resnet34-edgeaux-resume-stable-384
  seed: 42

extends: configs/isic2018_resnet34_edgeaux_finetune_384.yaml

training:
  batch_size: 32
  learning_rate: 0.00004
  num_workers: 2
  pin_memory: false
  persistent_workers: false
  prefetch_factor: 2
  init_checkpoint: runs/isic2018-resnet34-edgeaux-finetune-384-checkpoints/best.pt
  init_strict: true
  checkpoint_dir: runs/isic2018-resnet34-edgeaux-resume-stable-384-checkpoints
  scheduler:
    type: reduce_on_plateau
    factor: 0.5
    patience: 5
    min_lr: 0.000001
  early_stopping:
    enabled: true
    patience: 14
    min_delta: 0.0005
